[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=production npm install"

[deploy]
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.deploy]
startCommand = "npm start"