[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=production npm install"

[deploy]
startCommand = "NODE_ENV=production node /src/api.js"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10