[environments.production.build]
builder = "nixpacks"
buildCommand = "npm install"

[environments.production.deploy]
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

