[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Add production-specific environment variables here
[env.production]
NODE_ENV = "./config/production.json"
# Add other environment variables as needed
# SECRET_KEY = "your_production_secret_here"

# Consider adding a [scaling] section if your platform supports it, to handle load efficiently
# [scaling.production]
# instances = 2 # Example: Scale to 2 instances for handling more traffic
# autoScaling = true # Enable auto-scaling if supported and needed

# Additional configurations for monitoring, logging, or other production concerns can be added here

